// Code generated by hertz generator.

package test

import (
	"context"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	test "hertz_demo/biz/model/api/test"
)

// HelloMethod .
// @router /hello [GET]
func HelloMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req test.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(test.HelloResp)

	resp.RespBody = "hello," + req.Name

	c.JSON(consts.StatusOK, resp)
}

// TestGetMethod .
// @router /get [GET]
func TestGetMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req test.TestGetReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(test.TestGetResp)

	str_age := strconv.Itoa(int(req.Age))

	resp.Message = "你好," + str_age + "岁的" + req.Name

	c.JSON(consts.StatusOK, resp)
}

// TestPostMethod .
// @router /add [PUT]
func TestPostMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req test.TestPutReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(test.TestPutResp)

	str_age := strconv.Itoa(int(req.Age))

	resp.Message = str_age + "岁的" + req.Name + "插入成功"

	c.JSON(consts.StatusOK, resp)
}
