// Code generated by hertz generator.

package test

import (
	"context"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	test "hertz_demo/biz/model/hello/test"
)

// CommentAction .
// @router /api/test [POST]
func CommentAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req test.TestRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(test.TestResponse)

	age := strconv.Itoa(int(req.Age))

	resp.StatusMsg = "你好" + age + "岁的" + req.Name

	c.JSON(consts.StatusOK, resp)
}
