// Code generated by hertz generator.

package user

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"hertz_demo/biz/dal"
	"hertz_demo/biz/dbmodel"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	user "hertz_demo/biz/model/basic/user"
)

// CreateUser .
// @router /api/user/add [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.CreateUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.CreateUserResp)

	u := &dbmodel.User{
		Username: req.Username,
		Password: req.Password,
		Email:    req.Email,
	}
	hlog.Infof("age: %d, username: %s, email :%s", *req.Age, req.Username, *req.Email)

	if err = dal.CreateUser([]*dbmodel.User{u}); err != nil {
		c.JSON(consts.StatusInternalServerError, &user.CreateUserResp{Code: 400, Msg: err.Error()})
		return
	}

	c.JSON(consts.StatusOK, resp)
}
