// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "buyfakett",
            "url": "https://github.com/buyfakett"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/book/add": {
            "put": {
                "responses": {}
            }
        },
        "/api/book/delete/:book_id": {
            "delete": {
                "responses": {}
            }
        },
        "/api/book/list": {
            "get": {
                "responses": {}
            }
        },
        "/api/book/update/:book_id": {
            "post": {
                "responses": {}
            }
        },
        "/api/user/add": {
            "post": {
                "responses": {}
            }
        },
        "/api/user/change_passwd/:user_id": {
            "post": {
                "responses": {}
            }
        },
        "/api/user/delete/:user_id": {
            "post": {
                "responses": {}
            }
        },
        "/api/user/info/:user_id": {
            "get": {
                "responses": {}
            }
        },
        "/api/user/list": {
            "get": {
                "responses": {}
            }
        },
        "/api/user/login": {
            "post": {
                "responses": {}
            }
        },
        "/api/user/update/:user_id": {
            "post": {
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.1",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "hertz_service",
	Description:      "learn hertz by [buyfakett](https://github.com/buyfakett).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
