basePath: /api
info:
  contact:
    name: buyfakett
    url: https://github.com/buyfakett
  description: learn hertz by [buyfakett](https://github.com/buyfakett).
  title: hertz_service
  version: 0.1.1
paths:
  /api/book/add:
    put:
      responses: {}
  /api/book/delete/:book_id:
    delete:
      responses: {}
  /api/book/list:
    get:
      responses: {}
  /api/book/update/:book_id:
    post:
      responses: {}
  /api/user/add:
    post:
      responses: {}
  /api/user/change_passwd/:user_id:
    post:
      responses: {}
  /api/user/delete/:user_id:
    post:
      responses: {}
  /api/user/info/:user_id:
    get:
      responses: {}
  /api/user/list:
    get:
      responses: {}
  /api/user/login:
    post:
      responses: {}
  /api/user/update/:user_id:
    post:
      responses: {}
schemes:
- http
swagger: "2.0"
